%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPullSupplier
%% Source: /home/vagrant/build-dir_15-12-18_12-20-55/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPULLSUPPLIER_HRL, true).




-endif.


