%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyFilter_MappingFilter
%% Source: /home/vagrant/build-dir_15-12-18_12-20-55/otp-support/lib/cosNotification/src/CosNotifyFilter.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYFILTER_MAPPINGFILTER_HRL).
-define(COSNOTIFYFILTER_MAPPINGFILTER_HRL, true).




-endif.


