%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyChannelAdmin_EventChannelFactory
%% Source: /home/vagrant/build-dir_15-12-18_12-20-55/otp-support/lib/cosNotification/src/CosNotifyChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL).
-define(COSNOTIFYCHANNELADMIN_EVENTCHANNELFACTORY_HRL, true).




-endif.


