%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosNotifyComm_StructuredPushConsumer
%% Source: /home/vagrant/build-dir_15-12-18_12-20-50/otp-support/lib/cosNotification/src/CosNotifyComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL).
-define(COSNOTIFYCOMM_STRUCTUREDPUSHCONSUMER_HRL, true).




-endif.


