%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosEventComm_PullSupplier
%% Source: /home/vagrant/build-dir_15-12-18_12-20-55/otp-support/lib/cosEvent/src/CosEventComm.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSEVENTCOMM_PULLSUPPLIER_HRL).
-define(COSEVENTCOMM_PULLSUPPLIER_HRL, true).




-endif.


