%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: oe_CosEventChannelAdmin
%% Source: /home/vagrant/build-dir_15-12-18_12-20-55/otp-support/lib/cosEvent/src/CosEventChannelAdmin.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(OE_COSEVENTCHANNELADMIN_HRL).
-define(OE_COSEVENTCHANNELADMIN_HRL, true).




-endif.


