{application,nitrogen,
             [{description,"My Nitrogen Web Project"},
              {vsn,"1"},
              {registered,[]},
              {applications,[kernel,stdlib]},
              {mod,{nitrogen_app,[]}},
              {env,[]},
              {modules,[index,mobile,nitrogen_app,nitrogen_main_handler,
                        nitrogen_sup,nn_add_edit,nn_db_test,nn_lib,nn_mnesia,
                        nn_notes,nn_search]}]}.
