%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTime
%% Source: /home/vagrant/build-dir_15-12-18_12-20-50/otp-support/lib/cosTime/src/CosTime.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIME_HRL).
-define(COSTIME_HRL, true).


-record('CosTime_TimeUnavailable', {'OE_ID'="IDL:omg.org/CosTime/TimeUnavailable:1.0"}).


-endif.


