%%  coding: latin-1
%%------------------------------------------------------------
%%
%% Erlang header file
%% 
%% Target: CosTimerEvent_TimerEventService
%% Source: /home/vagrant/build-dir_15-12-18_12-20-50/otp-support/lib/cosTime/src/CosTimerEvent.idl
%% IC vsn: 4.4
%% 
%% This file is automatically generated. DO NOT EDIT IT.
%%
%%------------------------------------------------------------


-ifndef(COSTIMEREVENT_TIMEREVENTSERVICE_HRL).
-define(COSTIMEREVENT_TIMEREVENTSERVICE_HRL, true).




-endif.


